# Generated by Django 3.0.6 on 2020-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthwish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('message', models.CharField(max_length=256)),
                ('images', models.ImageField(blank=True, upload_to='pic')),
            ],
        ),
    ]
